### ISSUE TITLE
Refusing to install fbgraphapi as a dependency of itself

### ISSUE THREAD

**Issue by sohailriaz** [vanng822/facebook-nodejs#13]

**Comment by vanng822** [comment]
What is the problem now?

**Comment by vanng822** [comment]
@sohailriaz please specify problem since the title of the issue is not making sense.

**Comment by sohailriaz** [comment]
When i run this command to install fbgraphapi  ' npm install fbgraphapi ' 
fbgraphapi is not install and show this error

![capture](https://cloud.githubusercontent.com/assets/20614220/26719798/655f3aea-479f-11e7-9f25-27366e99ac4b.PNG)

**Comment by vanng822** [comment]
Please don't name your project the same as the package you are depending on. Rename your project to something else and try again

**Comment by sohailriaz** [comment]
Thank You so much

**Comment by vanng822** [comment]
NP
